### ISSUE TITLE
好小子，你居然备份了

### ISSUE THREAD

**Issue by 2567176308** [Cute-Dress/Dress#1]
我真的哭死

**Comment by Flysky12138** [comment]
我是说我的项目 [https://github.com/Flysky12138/PicW](https://github.com/Flysky12138/PicW) 预览地址看不了了

[https://picw.4everland.app/images?name=Dress-backup&repository=Dress&directory=/](https://picw.4everland.app/images?name=Dress-backup&repository=Dress&directory=/)

**Comment by CuteDress** [comment]
> 我是说我的项目 https://github.com/Flysky12138/PicW 预览地址看不了了
> 
> https://picw.4everland.app/images?name=Cute-Dress&repository=Dress&directory=/

挺不错的，已加入 README 6928df6
