### ISSUE TITLE
请问，都是带把的？

### ISSUE THREAD

**Issue by zhoufanglu** [Cute-Dress/Dress#26]
第三百六十四条【传播淫秽物品罪】 传播淫秽的书刊、影片、音像、图片或者其他淫秽物品，情节严重的，处二年以下有期徒刑、拘役或者管制。
　　组织播放淫秽的电影、录像等音像制品的，处三年以下有期徒刑、拘役或者管制，并处罚金；情节严重的，处三年以上十年以下有期徒刑，并处罚金。
　　制作、复制淫秽的电影、录像等音像制品组织播放的，依照第二款的规定从重处罚。
　　向不满十八周岁的未成年人传播淫秽物品的，从重处罚。

**Comment by CuteDress** [comment]
抱歉，不想看到本项目建议就不要点开来
