### ISSUE TITLE
第一次穿黑丝袜 ;>

### ISSUE THREAD

**Issue by FWKTzhang3** [Cute-Dress/Dress#33]
![d2bab2be968b87a7269c54b0d48cde48](https://github.com/Cute-Dress/Dress/assets/63797264/d2f58721-ec3f-4b3e-9894-eeec20bac289)
![f44dee93f55d0779509c187ffec98c5b](https://github.com/Cute-Dress/Dress/assets/63797264/06057322-6398-44fb-a5b5-228bca74f52b)

**Comment by FWKTzhang3** [comment]
![1](https://github.com/Cute-Dress/Dress/assets/63797264/912a9c5d-37e1-4d8f-9b54-9d8e54a223b9)
qi't
![2](https://github.com/Cute-Dress/Dress/assets/63797264/51aca162-d02b-4f86-99c1-7ec44b1a6654)

**Comment by CuteDress** [comment]
请学习 Git 及 GitHub 的使用方式，在 Pull Request 中提交，谢谢~(●'◡'●)
